language: csharp
solution: Web-Page-Screensaver.sln
install:
  - nuget restore Web-Page-Screensaver.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Web-Page-Screensaver.sln
#  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./WebpageScreensaver.Test/bin/Release/WebpageScreensaver.Test.dll --trace=Verbose
#  - mono OpenCover.Console.exe -register:user -target:"./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe" -targetargs:"./MyProject.Tests/bin/Release/MyProject.Tests.dll -noshadow" -filter:"+[UnitTestTargetProject*]* -[MyUnitTests*]*" -output:".\MyProject_coverage.xml"
#  - codecov -f "MyProject_coverage.xml" "93a81734-84ae-4432-9a05-8c523c674228"
 
