# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
     
- task: PublishPipelineArtifact@1
  inputs:
    path: $(System.DefaultWorkingDirectory)/bin/x86/Release
    artifact: ChromiumWebScreensaver

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/bin/x86/Release' 
    includeRootFolder: false 
    archiveType: 'zip' # Options: zip, 7z, tar, wim
    #tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
    archiveFile: '$(Build.ArtifactStagingDirectory)/ChromiumWebScreensaver_build_$(Build.BuildId).zip' 
    replaceExistingArchive: true 
    verbose: # Optional
    #quiet: # Optional
    
- task: GithubRelease@0 
  displayName: 'Create GitHub Release'      
  inputs:
    gitHubConnection: ZenProjects
    repositoryName: ZenProjects/Chromium-Web-Page-Screensaver
    tagSource: manual
    tag: $(Build.BuildNumber)      
    assets: |
         $(Build.ArtifactStagingDirectory)/ChromiumWebScreensaver_build_$(Build.BuildId).zip
